name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html

      - name: Run tests
        run: pytest test_simple.py --html=report.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Test-Artifacts
          path: |
            report.html
            calculator.py
            test_simple.py